name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Or any Linux runner
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    container:
      image: ubuntu:latest # Or any specific image
      options: "--mount type=bind,source=path/to/host/directory,target=path/to/container/directory" # Important if needing files

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up the operating system
      #   uses: actions/setup-os@v1
      #   with:
      #     os: ${{ matrix.os }} # Dynamically sets the OS

      - name: Run common steps
        run: |
          echo "This is a common step for all OSes"
          echo "Current OS: $(echo ${{ matrix.os }} | awk -F- '{print $1}')"  # Dynamic OS identification

      # OS-specific steps
      - name: Run Windows steps (if applicable)
        if: matrix.os == 'windows-latest'
        run: powershell -Command "Get-ItemProperty 'C:\Path\to\my\file.txt' | format-list" # Example
      - name: Run macOS steps (if applicable)
        if: matrix.os == 'macos-latest'
        run: |
          /bin/ls -l /tmp
          /Applications/my_application
      - name: Run Linux steps (inside a container)
        if: matrix.os == 'ubuntu-latest'
        run: |
          apt-get update && apt-get install -y file # Example command
          ls /tmp
          echo "This is a linux step inside a container"