name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: # This should be at the job level, not step level
      image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run common steps
        run: |
          echo "This is a common step for all OSes"
          echo "Current OS: ${{ matrix.os }}"  # Display the current OS

      # OS-specific steps
      - name: Run Windows steps (if applicable)
        if: matrix.os == 'windows-latest'
        run: powershell -Command "Get-Process | Select-Object -First 5" # List first 5 running processes

      - name: Run macOS steps (if applicable)
        if: matrix.os == 'macos-latest'
        run: |
          echo "Listing files in the home directory"
          ls -l ~ # List files in the home directory

      - name: Run Linux steps (inside a container)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Updating package list and installing curl"
          apt-get update && apt-get install -y curl # Install curl
          echo "Listing files in the root directory"
          ls -l / # List files in the root directory