name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Linux steps
        run: |
          echo "Updating package list and installing curl"
          apt-get update && apt-get install -y curl # Install curl
          echo "Listing files in the root directory"
          ls -l / # List files in the root directory

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run macOS steps
        run: |
          echo "Listing files in the home directory"
          ls -l ~ # List files in the home directory

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Windows steps
        run: powershell -Command "Get-Process | Select-Object -First 5" # List first 5 running processes